config/routes.rb
Dbox::Application.routes.draw do
  devise_for :users

  resources :groups, only: [ :index, :new, :show, :create, :edit, :update ] do
    member do
      post 'invite'
    end
  end

  resources :images, only: [ :index, :new, :show, :create ] do
    member do 
      post 'tag'
    end
  end

  root to: "static#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    unless user.nil?
        can :manage, :all
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessible :name


  validates :name, length: { in:  2..30 }

  has_and_belongs_to_many :users

end

app/models/image.rb
class Image < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_accessible :attachment

  has_attached_file :attachment

  validates_with AttachmentPresenceValidator, attributes: :attachment
  
  has_and_belongs_to_many :tags  

  belongs_to :user
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  # attr_accessible :title, :body
  #
  has_and_belongs_to_many :images

  validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_and_belongs_to_many :groups
  has_many :images
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  check_authorization :unless => :devise_controller?
  
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  load_and_authorize_resource

  def create
    group = Group.create(params[:group])
    redirect_to group
  end

  def edit
    group = Group.find(params[:id])
  end

  def update
    group = Group.find(params[:id])
    group.update_attributes(params[:group])
    redirect_to group
  end

  def invite
    group = Group.find(params[:id])
    puts params[:email]

    user = User.find_by_email(params[:email])

    unless user.nil?
      group.users << user
    end

    redirect_to group
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  load_and_authorize_resource
  
  def index
  	@images = Image.all
  end

  def show
    @image = Image.find(params[:id])
  end

  def new
  	@image = Image.new
  end

  def create
  	@image = Image.create(params[:image])
    puts current_user
    @image.user = current_user
    @image.save

  	redirect_to images_path
  end

  def tag
    @image = Image.find(params[:id])
    tag = Tag.find_or_create_by_name(params[:name])

    @image.tags << tag

    redirect_to @image
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  skip_authorization_check
  def index
    render :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/groups/edit.html.haml
%h3
  Edit group

= form_for @group do |f|
  Name: 
  = f.text_field :name
  = f.submit 'Save'

app/views/groups/index.html.haml
%h3
  All groups

= link_to 'New', new_group_path
%ul
  - @groups.each do |group|
    %li
      = link_to group.name, group

app/views/groups/new.html.haml
%h3
  New group

= form_for @group do |f|
  = f.text_field :name
  = f.submit 'Create'

app/views/groups/show.html.haml
%h3
  Group

= link_to 'Edit', edit_group_path(@group)

Name: 
= @group.name

%h4
  Add member to group:
= form_tag invite_group_path do
  = text_field_tag :email
  = submit_tag 'Invite'
  
%h4
  All members
%ul
  - @group.users.each do |user|
    = user.email

app/views/images/index.html.haml
= link_to 'New', new_image_path

%ul
  - @images.each do |image|
    %li
      = link_to image.attachment_file_name, image

app/views/images/new.html.haml
%h3
  Upload a new file
= form_for @image do |f|
  = f.file_field :attachment
  = f.submit 'Upload'

app/views/images/show.html.haml
%h3
  This is an image
File name:
= @image.attachment_file_name

%br
The image:
= image_tag @image.attachment.url


%h4
  All tags on this image

= form_tag tag_image_path(@image) do
  = label_tag "tag it:"
  = text_field_tag :name
  = submit_tag "Tag it!"
  
%ul.images
  - @image.tags.each do |tag|
    %li
      = tag.name

app/views/layouts/application.html.haml
%html
  %head
  %title
    Dbox
  = stylesheet_link_tag    "application", :media => "all"
  = stylesheet_link_tag    "http://fonts.googleapis.com/css?family=Tangerine"
  = stylesheet_link_tag    "http://fonts.googleapis.com/css?family=Lato"
  = stylesheet_link_tag    "http://fonts.googleapis.com/css?family=MoseoSans"
  = stylesheet_link_tag    "http://fonts.googleapis.com/css?family=Fontin"

  = javascript_include_tag "application"
  = csrf_meta_tags
%body
  = render 'shared/header'

  .flash
    %p.alert
      = flash[:alert]
    %p.notice
      = flash[:notice]

.content  
  = yield

app/views/shared/_header.html.haml
.header
  .title
    dbox

  %ul.menu
    - unless user_signed_in?
      %li= link_to "signin", new_user_session_path
    - else
      %li= link_to "signout", destroy_user_session_path, method: :delete
      %li= current_user.email